"""add promo_price and image column to products table

Revision ID: 19efd166edcb
Revises: 21680668173f
Create Date: 2025-04-23 04:44:55.128115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '19efd166edcb'
down_revision: Union[str, None] = '21680668173f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('price_promo', sa.Float(), nullable=True))
    op.add_column('products', sa.Column('image', sa.String(length=255), nullable=True))
    op.drop_column('products', 'tax_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('tax_type', mysql.ENUM('none', 'ppn'), nullable=True))
    op.drop_column('products', 'image')
    op.drop_column('products', 'price_promo')
    # ### end Alembic commands ###
